name: aeroleads-task-a
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.1.3
  - lxml
  - pip
  - pip:
    - selenium==4.15.2
    - undetected-chromedriver==3.5.4
    - python-dotenv==1.0.0
    - beautifulsoup4==4.12.2
    - webdriver-manager==4.0.1
